# Generated by Django 4.2.11 on 2024-05-03 15:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('chatId', models.BigAutoField(primary_key=True, serialize=False)),
                ('chats', models.TextField(blank=True, max_length=1024, null=True)),
                ('audio', models.FileField(blank=True, null=True, upload_to='')),
                ('status', models.CharField(choices=[('read', 'read'), ('unread', 'unread'), ('delivered', 'delivered'), ('typing', 'typing')], max_length=10)),
                ('createdBy', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('modifiedBy', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagId', models.UUIDField(default=uuid.uuid4)),
                ('tagged', models.SlugField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('modifiedBy', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('fullName', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('online', 'online'), ('offline', 'offline')], default='offline', max_length=50)),
                ('active', models.BooleanField(default=False)),
                ('profilePic', models.ImageField(blank=True, null=True, upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('createdBy', models.CharField(max_length=100)),
                ('modifiedBy', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['userId'],
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('threadId', models.BigAutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField(max_length=1024, null=True)),
                ('fileComment', models.FileField(upload_to='')),
                ('imageComment', models.ImageField(blank=True, null=True, upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('modifiedBy', models.CharField(blank=True, max_length=100)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replied', to='whatsappServiceApi.message')),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('statusId', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('video', models.FileField(blank=True, null=True, upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('modifiedBy', models.CharField(blank=True, max_length=100)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whatsappServiceApi.user')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('roomId', models.BigAutoField(primary_key=True, serialize=False)),
                ('roomName', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('modifiedBy', models.CharField(blank=True, max_length=100)),
                ('users', models.ManyToManyField(to='whatsappServiceApi.user')),
            ],
        ),
        migrations.CreateModel(
            name='ResetPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oldPassword', models.CharField(max_length=150)),
                ('newPassword', models.CharField(max_length=150)),
                ('confirmPassword', models.CharField(max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('modifiedBy', models.CharField(blank=True, max_length=100)),
                ('resetUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whatsappServiceApi.user')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='fromUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='whatsappServiceApi.user'),
        ),
        migrations.AddField(
            model_name='message',
            name='taggedUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whatsappServiceApi.tag'),
        ),
        migrations.AddField(
            model_name='message',
            name='toUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to='whatsappServiceApi.user'),
        ),
    ]
